// <auto-generated />
#pragma warning disable CS0105
using KC;
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System;
using KC.Tables;

namespace KC
{
   public sealed class DatabaseBuilder : DatabaseBuilderBase
   {
        public DatabaseBuilder() : this(null) { }
        public DatabaseBuilder(MessagePack.IFormatterResolver resolver) : base(resolver) { }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<Sample2MasterData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<long>.Default);
            return this;
        }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<Sample3MasterData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<long>.Default);
            return this;
        }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<SampleMasterData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<long>.Default);
            return this;
        }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<SampleMultiMasterData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<long>.Default);
            return this;
        }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<SampleProbMasterData> dataSource)
        {
            AppendCore(dataSource, x => x.Id, System.Collections.Generic.Comparer<long>.Default);
            return this;
        }

    }
}